networks:
  megaservice_network:
    external: true

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-server
    ports:
      - "5678:5678"
    networks:
      - megaservice_network
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
      - NODE_ENV=production
      - N8N_LOG_LEVEL=debug
      - N8N_LOG_OUTPUT=console
      - CODE_ENABLE_STDOUT=true
      - N8N_EDITOR_BASE_URL=http://localhost:5678
      - N8N_HOST=localhost
      - N8N_PROTOCOL=http
      - N8N_PORT=5678
      - N8N_WEBHOOK_TEST_URL=false
    user: node
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  n8n_data:
    external: true
    name: n8n_data
